# SPDX-FileCopyrightText: 2022-2025 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Summarize Test Results

author: Paul Colby

description: Summarise TAP (Test Anything Protocol) test results

inputs:
  path:
    description: One or more paths to TAP files
    required: true
    default: '**/*.tap'
  summary-file:
    description: File to append TAP summary to
    required: false

outputs:
  summary-file:
    description: File TAP summary was appended to
    value: ${{ steps.tap.outputs.summary-file }}

runs:
  using: composite
  steps:
    - run: |
        set -o errexit -o noclobber -o nounset -o pipefail
        [[ -z "$(shopt globstar 2> /dev/null)" ]] && echo 'Shell does not support globstar' || shopt -s globstar
        : "${SUMMARY_FILE:=$GITHUB_STEP_SUMMARY}"
        paths=(${{ inputs.path }}) # Expand globs, and trim whitespce.
        gawk --file "$GITHUB_ACTION_PATH/summary.gawk" --sandbox -- "${paths[@]}" >> "$SUMMARY_FILE"
        echo "summary-file=$SUMMARY_FILE" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        SUMMARY_FILE: ${{ inputs.summary-file }}
      id: tap

branding:
  color: green
  icon: check
