# SPDX-FileCopyrightText: 2022-2025 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Lint Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Check Markdown files
        run: npm install markdownlint-cli2 --global && markdownlint-cli2
      - name: Check shell scripts
        run: find . -name '*.sh' -print -execdir shellcheck --check-sourced --enable=all --external-sources --norc {} +
      - name: Check YAML files
        run: yamllint --strict .
      - name: Check run scripts
        uses: pcolby/check-run-scripts@v0.3
        with:
          paths: |-
            ${{ github.workspace }}/.github/workflows
            action.yaml
          external-variables: EXTRA_DIFF_ARGS
