# SPDX-FileCopyrightText: 2022-2025 Paul Colby <git@colby.id.au>
# SPDX-License-Identifier: MIT

name: Lint Checks

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: shellcheck --enable=all --norc test/test.sh
